[build]
  publish = "public"  # HTML、CSSなどを配置する公開ディレクトリ
  functions = "functions"  # Netlify Functionsのコードを置くディレクトリ

[[redirects]]
  from = "/webhook"
  to = "/.netlify/functions/lineWebhook"
  status = 200

